In [2]:
import numpy as np

In [11]:
xy_means=np.array([-9.3,-1.3,5.7,6.5])
xy_stds=np.array([8.2,8.4,8.2,8.3])
xy_cor=np.array([[1,-0.1,-0.05,0.1],[-0.1,1,0.1,-0.05],[-0.05,0.1,1,0.1],[0.1,-0.05,0.1,1]])
xy_cov=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
for i in range(4):
    for j in range(4):
        xy_cov[i][j]=xy_stds[i]*xy_stds[j]*xy_cor[i][j]
print(xy_cov)

[[67.24, -6.888, -3.362, 6.806000000000001], [-6.888, 70.56, 6.888, -3.4860000000000007], [-3.362, 6.888, 67.24, 6.806000000000001], [6.806000000000001, -3.4860000000000007, 6.806000000000001, 68.89000000000001]]


In [ ]:
# Estimate the values of (r, delta, gamma)
r=np.sqrt(xy_means[0]**2+xy_means[1]**2)+np.sqrt(xy_means[2]**2+xy_means[3]**2)
r=r/2
print('r:',r)
dpg=np.arctan(xy_means[1]/xy_means[0])
dmg=np.arctan(xy_means[3]/xy_means[2])
delta=(dpg+dmg)/2
gamma=(dpg-dmg)/2
print('delta:',delta)
print('gamma:',gamma)

r: 9.01782527473759
delta: 0.4948816019205631
gamma: -0.35599658640035003


In [25]:
# Estimate the values of (sigma_r, sigma_delta, sigma_gamma)
import jacobi as jacobi
from jacobi import propagate

# propagate to parameter estimates

def f_radius(xp, yp, xm , ym):
    return (np.sqrt(xp**2 + yp**2) + np.sqrt(xm**2 + ym**2)) / 2

def f_delta(xp, yp, xm , ym):
    return (np.arctan(yp / xp) + np.arctan(ym / xm)) / 2

def f_gamma(xp, yp, xm , ym):
    return (np.arctan(yp / xp) - np.arctan(ym / xm)) / 2

# jacobi needs a single wrapped function
rdg = lambda p: np.array([ f_radius(*p), f_delta(*p), f_gamma(*p) ])

rdg_vals, rdg_cov = propagate(rdg, xy_means, xy_cov)
print('Values (r, delta, gamma):', *rdg_vals)
print('Uncertainties:', *np.sqrt(np.diag(rdg_cov)))
print(rdg_cov)
rdg_corr = np.corrcoef(rdg_cov)
print(rdg_corr)

Values (r, delta, gamma): 9.01782527473759 0.4948816019205631 -0.35599658640035003
Uncertainties: 5.789179951859979 0.6793756821115084 0.5986414189630754
[[ 3.35146045e+01 -3.77197564e-01 -3.11539756e-02]
 [-3.77197564e-01  4.61551317e-01  4.78248414e-04]
 [-3.11539756e-02  4.78248414e-04  3.58371548e-01]]
[[ 1.         -0.84079046 -0.55460168]
 [-0.84079046  1.          0.01582892]
 [-0.55460168  0.01582892  1.        ]]
